# Generated by Django 3.1.1 on 2020-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('BookOneName', models.CharField(max_length=150)),
                ('BookOneUrl', models.URLField(max_length=500)),
                ('BookTwoName', models.CharField(max_length=150)),
                ('BookTwoUrl', models.URLField(max_length=500)),
                ('BookThreeName', models.CharField(max_length=150)),
                ('BookThreeUrl', models.URLField(max_length=500)),
                ('BookFourName', models.CharField(max_length=150)),
                ('BookFourUrl', models.URLField(max_length=500)),
                ('BookFiveName', models.CharField(max_length=150)),
                ('BookFiveUrl', models.URLField(max_length=500)),
                ('BookSixName', models.CharField(max_length=150)),
                ('BookSixUrl', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GovJobPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=150)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='Index/images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
