# Generated by Django 3.1.1 on 2020-11-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gjob', '0002_latestgovjobpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GovJobPost',
        ),
    ]
