# Generated by Django 3.1.1 on 2020-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gjob', '0003_delete_govjobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GjobPageContact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=50)),
            ],
        ),
    ]
