# Generated by Django 3.1.1 on 2020-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermBet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('stockname', models.CharField(max_length=150)),
                ('intrinscivalue', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PreviousSwingTrade',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('stockname', models.CharField(max_length=150)),
                ('priceandaction', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('cardheading', models.CharField(max_length=150)),
                ('stockname1', models.CharField(max_length=150)),
                ('stockname2', models.CharField(max_length=150)),
                ('stockname3', models.CharField(max_length=150)),
                ('stockname4', models.CharField(max_length=150)),
                ('stockname5', models.CharField(max_length=150)),
                ('id', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SwingTradePost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('stockname', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('priceandaction', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
