# Generated by Django 3.1.1 on 2020-11-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketPageContact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=50)),
            ],
        ),
    ]
