# Generated by Django 3.1.1 on 2020-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_stockmarketpagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketOpinion',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('stockmarketopinionslug', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
