# Generated by Django 3.1.1 on 2020-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceNewsPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=150)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='Index/images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='HeaderNewsPics',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('HeaderNewsImage1', models.ImageField(default='', upload_to='Index/images')),
                ('HeaderNewsImage2', models.ImageField(default='', upload_to='Index/images')),
                ('HeaderNewsImage3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
        migrations.CreateModel(
            name='SideNewsPics',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('SideNewsImage1', models.ImageField(default='', upload_to='Index/images')),
                ('SideNewsImage2', models.ImageField(default='', upload_to='Index/images')),
                ('SideNewsImage3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
    ]
