# Generated by Django 3.1.1 on 2020-11-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceNews', '0002_latestfinancenewspost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceNewsPost',
        ),
    ]
